- anchor
- android
- archive
- apple
- battery-4
- automobile
- barcode
- balance-scale
- birthday-cake
- bell
- beer
- black-tie
- bitcoin
- bullhorn
- bullseye
- bluetooth-b
- binoculars
- bolt
- book
- briefcase
- bug
- building
- cab
- calculator
- calendar
- camera
- chain
- chrome
- clock-o
- cloud
- code-fork
- cog
- code
- coffee
- comment
- compass
- cutlery
- dashboard
- database
- diamond
- exclamation-circle
- fighter-jet
- fire
- fire-extinguisher
- futbol-o
- gamepad
- gavel
- fort-awesome
- glass
- globe
- hand-lizard-o
- heartbeat
- hourglass
- inbox
- industry
- info-circle
- html5
- heart
- institution
- jpy
- leaf
- life-saver
- lightbulb-o
- link
- magic
- lock
- magnet
- map
- map-signs
- medkit
- microphone
- motorcycle
- newspaper-o
- paper-plane
- paperclip
- pencil
- phone
- plane
- puzzle-piece
- plug
- plus-circle
- pied-piper
- rocket
- recycle
- refresh
- ship
- shopping-bag
- shopping-cart
- star
- taxi
- terminal
- thumbs-up
- train
- television
- tree
- truck
- users
- trophy
- umbrella
- video-camera